name: Publish ethtool Exporter

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the image should be build
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/prometheus-ethtool-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true